import os
from forensic_analyzer.models.finding import ReportModel
from forensic_analyzer.utils.logger import get_logger

logger = get_logger("forensic.rules")

class DefenseRulesGenerator:
    """Génère automatiquement des règles YARA et Snort/Suricata depuis les IOCs trouvés."""

    def generate(self, report: ReportModel, output_dir: str = "."):
        """Analyse le rapport complet et exporte les règles de défense."""
        
        md5_hashes = set()
        ips = set()
        urls = set()
        
        # 1. Collecter tous les IOCs
        for finding in report.findings:
            if "MD5" in finding.metadata:
                md5_hashes.add(finding.metadata["MD5"])
            
            # Extract from 'extra'
            if "hardcoded_iocs" in finding.extra:
                ips.update(finding.extra["hardcoded_iocs"].get("ips", []))
                urls.update(finding.extra["hardcoded_iocs"].get("urls", []))
                
            if "pdf_urls" in finding.extra:
                urls.update(finding.extra["pdf_urls"])
                
            if "pcap_dns_requests" in finding.extra:
                for dns in finding.extra["pcap_dns_requests"]:
                    urls.add(dns.get("query", ""))
                    
            if finding.type == "ids_alerts" and "raw_alerts" in finding.extra:
                for alert in finding.extra["raw_alerts"]:
                    if "dest_ip" in alert and alert["dest_ip"]:
                        ips.add(alert["dest_ip"])
                
        # Nettoyage
        ips = {ip for ip in ips if ip and not ip.startswith("192.168.") and not ip.startswith("10.") and not ip.startswith("127.")}
        urls = {url for url in urls if url and "." in url}
        
        if not md5_hashes and not ips and not urls:
            logger.debug("Aucun IOC pertinent trouvé. Pas de génération de règles de défense.")
            return
            
        logger.info(f"Génération des règles de défense ({len(md5_hashes)} Hash, {len(ips)} IPs, {len(urls)} URLs)...")
        
        os.makedirs(output_dir, exist_ok=True)
        
        # 2. Générer YARA (Pour les Endpoint / EDR)
        yara_path = os.path.join(output_dir, "auto_generated.yar")
        with open(yara_path, "w", encoding="utf-8") as f:
            f.write("/*\n")
            f.write("  YARA Rules Generated by Forensic Analyzer\n")
            f.write("*/\n\n")
            f.write("import \"hash\"\n\n")
            
            if md5_hashes:
                f.write("rule Forensic_Suspicious_Hashes {\n")
                f.write("    meta:\n")
                f.write('        description = "Detects extracted suspicious files"\n')
                f.write('        author = "Forensic Analyzer"\n')
                f.write("    condition:\n")
                conditions = [f'hash.md5(0, filesize) == "{h.lower()}"' for h in md5_hashes]
                f.write("        " + " or ".join(conditions) + "\n")
                f.write("}\n\n")
                
            if urls:
                f.write("rule Forensic_Suspicious_Strings {\n")
                f.write("    meta:\n")
                f.write('        description = "Detects files containing malicious URLs"\n')
                f.write("    strings:\n")
                for i, url in enumerate(urls):
                    f.write(f'        $url{i} = "{url}" ascii wide nocase\n')
                f.write("    condition:\n")
                f.write("        any of them\n")
                f.write("}\n")
                
        # 3. Générer Suricata/Snort (Pour le Réseau)
        snort_path = os.path.join(output_dir, "auto_generated.rules")
        sid = 1000000
        with open(snort_path, "w", encoding="utf-8") as f:
            f.write("# Suricata/Snort Rules Generated by Forensic Analyzer\n")
            
            for ip in ips:
                f.write(f'alert tcp $HOME_NET any -> {ip} any (msg:"Suspicious Connection to Extracted IOC IP"; sid:{sid}; rev:1;)\n')
                sid += 1
                
            for url in urls:
                domain = url.replace("http://", "").replace("https://", "").split("/")[0]
                if domain:
                    f.write(f'alert dns $HOME_NET any -> any any (msg:"Suspicious DNS Query to Extracted Domain"; dns.query; content:"{domain}"; sid:{sid}; rev:1;)\n')
                    sid += 1
                
        logger.info(f"Règles YARA sauvegardées dans {yara_path}")
        logger.info(f"Règles Suricata/Snort sauvegardées dans {snort_path}")
